version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=5000
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always  # Ajout du restart

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip", "0.0.0.0"]  # Forcer l'écoute sur toutes les interfaces

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16  # Forcer une plage IPv4

volumes:
  mongo-data: