services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"  # Permettre l'utilisation des ports 5000 ou 5001
    environment:
      - MONGO_URI=mongodb://mongo:27017/todos
      - PORT=5000  # Port par défaut, sera ajusté dynamiquement si nécessaire
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always
    volumes:
      - ./backend:/app:rw,cached

  frontend:
    build:
      context: ./frontend
      target: dev
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/app:rw,cached

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    command: ["--bind_ip", "0.0.0.0"]  # Forcer l'écoute sur toutes les interfaces

networks:
  app-network:

volumes:
  mongo-data: